config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  namespace :admin do
      resources :products
      get 'home', to: 'home#index'
  end
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :price, :quantity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    class AuthorizationError < StandardError; end
    layout 'admin'
    before_action :authorize_admin!

    rescue_from AuthorizationError do |e|
      flash[:error] = e.message
      redirect_to root_path
    end

    private

    def authorize_admin!
      return if current_user.present? && current_user.admin

      raise AuthorizationError, 'You are not permitted to access this page or it does not exist'
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < BaseController

    def index
      @products = Product.all # Heres the previously missing line
      @users_count = User.all.size
      @products_count = Product.all.size
      render :index, locals: { users_count: @users_count, products_count: @products_count }
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::BaseController
    # GET /products
    def index
      @products = Product.all
    end

    # GET /products/1
    def show
      @product = product
    end

    # GET /products/new
    def new
      render :form, locals: { product: Product.new, method: :post, url: admin_products_path }
    end

    # GET /products/1/edit
    def edit
      render :form, locals: { product:, method: :put, url: admin_product_path(product) }
    end

    # POST /products
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        else
          format.html do
            render :form, status: :unprocessable_entity, notice: 'Error',
                          locals: { product: @product, url: admin_products_path, method: :post }
          end
        end
      end
    end

    # PATCH/PUT /products/1
    def update
      @product = product
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        else
          format.html do
            render :form, status: :unprocessable_entity,
                          locals: { product:, method: :put, url: admin_product_path(product) }
          end
        end
      end
    end

    # DELETE /products/1
    def destroy
      product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def product
      @product ||= Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/home/index.html.erb
<div class="column is-9">

  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href=<%=admin_home_path %>>Admin</a></li>
      <li><a href=<%=admin_home_path %>>Home</a></li>
      <li class="is-active" aria-current="page"><a href=<%=admin_products_path %>>Products</a></li>
    </ul>
  </nav>
  <div class="container">
    <table class="table is-bordered is-hoverable is-fullwidth is-striped" >
      <thead>
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
      </tfoot>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td> <%= product.id %></td>
          <td> <%= product.name %></td>
          <td> <%= product.price %> $</td>
          <td> <%= product.quantity %></td>
          <td>
            <div class="field is-grouped">
              <p class="control">
                <button class="button is-small is-warning"><%= link_to 'Show', admin_product_path(product), class: "has-text-white" %></button>
              </p>
              <p class="control">
                <button class="button is-small is-link"><%= link_to 'Edit', edit_admin_product_path(product), class: "has-text-white" %></button>
              </p>
              <p class="control">
                <button class="button is-small is-danger"><%= link_to 'Destroy', admin_product_path(product), class: "has-text-white", method: :delete, data: { confirm: 'Are you sure?' } %></button>
              </p>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="container mt-5">
    <button class="button is-info"><%= link_to 'New Product', new_admin_product_path, class: "has-text-white" %></button>
  </div>
</div>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
</div>

app/views/admin/products/form.html.erb
<section class="column is-9">
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href=<%=admin_home_path %>>Admin</a></li>
      <li><a href=<%=admin_home_path %>>Home</a></li>
      <li><a href=<%=admin_products_path %>>Products</a></li>
      <% if method == :post %>
        <li class="is-active" aria-current="page"><a href=<%=new_admin_product_path %>>New Product</a></li>
      <% else %>
        <li class="is-active" aria-current="page"><a href=<%=edit_admin_product_path(product) %>>Edit <%=product.name %></a></li>
      <% end %>

    </ul>
  </nav>
  <div class="container">
    <%= form_with url: url, method: method, model: product do |form| %>
      <div class="control">

        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Name</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control has-icons-left">
                <%= form.text_field :name, class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-box"></i>
                </span>
              </p>
            </div>
          </div>
        </div>

        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Price</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control has-icons-left">
                <%= form.number_field :price, class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-dollar-sign"></i>
                </span>
              </p>
            </div>
          </div>
        </div>

        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Quantity</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control has-icons-left">
                <%= form.number_field :quantity, class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-archive"></i>
                </span>
              </p>
            </div>
          </div>
        </div>

        <div class="field is-horizontal">
          <div class="field-label">
            <!-- Left empty for spacing -->
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                <button type="submit" class="button is-primary">
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/admin/products/index.html.erb
<section class="section">
  <p id="notice"><%= notice %></p>

  <div class="container">
    <h1 class="title">Products</h1>
    <h2 class="subtitle">
      A simple products index page
    </h2>
    <table class="table is-bordered is-hoverable is-fullwidth is-striped" >
      <thead>
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Actions</th>
      </tr>
      </tfoot>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td> <%= product.id %></td>
          <td> <%= product.name %></td>
          <td>
            <div class="field is-grouped">
              <p class="control">
                <button class="button is-small is-warning"><%= link_to 'Show', admin_product_path(product) %></button>
              </p>
              <p class="control">
                <button class="button is-small is-link"><%= link_to 'Edit', edit_admin_product_path(product) %></button>
              </p>
              <p class="control">
                <button class="button is-small is-danger"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></button>
              </p>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="container mt-5">
    <button class="button is-info"><%= link_to 'New Product', new_admin_product_path %></button>
  </div>
</section>

app/views/admin/products/show.html.erb
<!--For now this view is just another table until out products have more going on. Treat this as a nice looking placeholder-->
<div class="column is-9">
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href=<%=admin_home_path %>>Admin</a></li>
      <li><a href=<%=admin_home_path %>>Home</a></li>
      <li><a href=<%=admin_products_path %>>Products</a></li>
      <li class="is-active" aria-current="page"><a href=<%=admin_product_path(@product) %>><%=@product.name %></a></li>
    </ul>
  </nav>
  <div class="container">
    <table class="table is-bordered is-hoverable is-fullwidth is-striped" >
      <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
        <tr>
          <td> <%= @product.name %></td>
          <td> <%= @product.price %> $</td>
          <td> <%= @product.quantity %></td>
          <td>
            <div class="field is-grouped">
              <p class="control">
                <button class="button is-small is-link"><%= link_to 'Edit', edit_admin_product_path(@product), class: "has-text-white" %></button>
              </p>
              <p class="control">
                <button class="button is-small is-danger"><%= link_to 'Destroy', admin_product_path(@product), class: "has-text-white", method: :delete, data: { confirm: 'Are you sure?' } %></button>
              </p>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
  </head>
  <body>
    <nav class="navbar is-white">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item brand-text" href=<%= admin_home_path %>>
            Shop Admin
          </a>
          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href=<%=admin_home_path %>>
              Home
            </a>
            <a class="navbar-item" href=<%=admin_products_path %>>
              Products
            </a>
            <a class="navbar-item" href=<%=admin_home_path %>>
              TODO
            </a>
            <a class="navbar-item" href=<%=admin_home_path %>>
              TODO
            </a>
            <a class="navbar-item" href=<%=admin_home_path %>>
              TODO
            </a>
          </div>

        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="columns">
        <div class="column is-3 ">
          <aside class="menu is-hidden-mobile">
            <p class="menu-label">
              General
            </p>
            <ul class="menu-list">
              <li><a class="is-active">Dashboard</a></li>
              <li><a>Customers</a></li>
            </ul>
            <p class="menu-label">
              Administration
            </p>
            <ul class="menu-list">
              <li><a>Team Settings</a></li>
              <li>
                <a>Manage Your Team</a>
                <ul>
                  <li><a>Members</a></li>
                  <li><a>Add a member</a></li>
                  <li><a>Remove a member</a></li>
                </ul>
              </li>
              <li><a>Invitations</a></li>
            </ul>
            <p class="menu-label">
              Transactions
            </p>
            <ul class="menu-list">
              <li><a>Payments</a></li>
              <li><a>Transfers</a></li>
              <li><a>Balance</a></li>
              <li><a>Reports</a></li>
            </ul>
          </aside>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification is-success"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-warning"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="notification is-danger"><%= flash[:error] %></div>
    <% end %>
    <% if current_user.present? %>
		  <nav class="navbar is-danger is-spaced" role="navigation" aria-label="main navigation">
		    <div class="navbar-brand">

		      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
		        <span aria-hidden="true"></span>
		        <span aria-hidden="true"></span>
		        <span aria-hidden="true"></span>
		      </a>
		    </div>

		    <div id="navbar" class="navbar-menu">
		      <div class="navbar-start">
		        <div class="navbar-item">
		          <span class="icon">
		            <i class="icon fas fa-th-list" aria-hidden="true"></i>
		          </span>
		          <span><%= link_to 'Products', products_path, class: "has-text-white" %></span>
		        </div>
		        <a class="navbar-item">
		          <span class="icon">
		            <i class="icon fas fa-shopping-cart" aria-hidden="true"></i>
		          </span>
		          <span>Cart</span>
		        </a>

		        <div class="navbar-item has-dropdown is-hoverable">
		          <a class="navbar-link">
		            More
		          </a>

		          <div class="navbar-dropdown">
		            <a class="navbar-item">
		              TODO
		            </a>
		            <a class="navbar-item">
		              TODO
		            </a>
		            <a class="navbar-item">
		              TODO
		            </a>
		            <hr class="navbar-divider">
		            <a class="navbar-item">
		              Report a bug
		            </a>
		          </div>
		        </div>
		      </div>

		      <div class="navbar-end">
		        <div class="navbar-item">
		          <div class="buttons">
		            <button class="button is-warning">
                  <%= link_to 'Log Out', destroy_user_session_path, class: "has-text-danger" %>
		            </button>
		          </div>
		        </div>
		      </div>
		    </div>
		  </nav>
		<% end %>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/products/index.html.erb
<section class="hero has-background-danger-dark	 is-small">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title has-text-light	">
        Products
      </p>
      <p class="subtitle has-text-light	">
        Here is what we offer
      </p>
    </div>
  </div>
</section>
<div class="box cta">
  <p class="has-text-centered">
    Click on selected product to see more details
  </p>
</div>
<section class="container">
  <% @products.each_slice(3) do |batch| %>
    <div class="columns features">
    <% batch.each do |product| %>
      <div class="column is-4">
        <div class="card is-shady">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="https://fuzati.com/wp-content/uploads/2016/12/Ruby-Logo.png" alt="Placeholder image" class="modal-button" data-target="modal-image2">
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <h5><%= product.name %></h5>
              <h6><%= product.price %></h6>
              <div>
                In stock: <span class="is-size-6 has-text-weight-semibold	"><%= product.quantity %></span>
              </div>
              <div class="columns is-vcentered">
                <div class="column">
                  <span class="button is-link">
                    <%= link_to(product) do %>
                      <span class="has-text-white is-size-6 has-text-weight-semibold">Details</span>
                    <% end %>
                  </span>
                </div>
                <div class="column">
                  <span class="icon is-small">
                    <i class="fas fa-shopping-cart" aria-hidden="true"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</section>

app/views/products/show.html.erb
<section class="hero is-primary ">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Product: <strong><%= @product.name %></strong>
      </h1>
      <h2 class="subtitle">
        Price: <strong><%= @product.price %></strong>
      </h2>
    </div>
  </div>
</section>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-256x256">
         <img src="https://fuzati.com/wp-content/uploads/2016/12/Ruby-Logo.png" alt="Image">
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <h5>
          <strong><%= @product.name %></strong> <small>in stock:</small> <small><%= @product.quantity %></small>
          <br>
        </h5>
        <h6>More content wil get here once our products can store more data and are in general more interesting items to work with.</h6>
      </div>
      <nav class="level">
        <div class="level-left">
          <a class="level-item" aria-label="subscribe">
            <span class="icon is-small">
              <i class="fas fa-flag" aria-hidden="true"></i>
              <!--TODO this will create a subscription to an item that is out of stock to receive an email when it is in stock again-->
            </span>
          </a>
          <a class="level-item" aria-label="cart">
            <span class="icon is-small">
              <i class="fas fa-shopping-cart" aria-hidden="true"></i>
              <!--TODO this will add item to cart-->
            </span>
          </a>
          <a class="level-item" aria-label="like">
            <span class="icon is-small">
              <i class="fas fa-heart" aria-hidden="true"></i>
              <!--TODO this will add item to favorites-->
            </span>
          </a>
        </div>
      </nav>
    </div>
  </article>
</div>